-- Operator-editable configuration (mail relay), so the founder can set SMTP
-- from the admin area rather than through Coolify environment variables.
--
-- Hand-written rather than generated by `prisma migrate dev`: that needs a
-- shadow database this machine does not have. The statements below are the
-- additive subset Prisma would emit for the AppSetting model — no existing
-- table is touched, so it is safe to replay.

CREATE TABLE "AppSetting" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "encrypted" BOOLEAN NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedById" TEXT NOT NULL,

    CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("key")
);

ALTER TABLE "AppSetting" ADD CONSTRAINT "AppSetting_updatedById_fkey"
    FOREIGN KEY ("updatedById") REFERENCES "AdminUser"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- The app role has no DDL rights (verified in production: has_schema_privilege
-- on public CREATE = false), so this migration runs as towardpcc_owner and must
-- hand the new table's DML back to the app role explicitly. Without this the
-- table exists and every read from the application fails with "permission
-- denied for table AppSetting".
--
-- Guarded so the migration still applies on a database that has no such role,
-- which is every developer machine and CI.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'towardpcc_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "AppSetting" TO towardpcc_app;
  END IF;
END
$$;
