import { COLONISATION, VESSELS } from "./anatomy";
import { insideLung, lobeAt } from "./envelope";
import { cardiacField } from "./heart";
import { mulberry32 } from "./rng";
import type { Lobe, TreeGeometry } from "./tree";

/**
 * The pulmonary circulation: arteries that travel WITH the bronchi, veins that
 * deliberately do not.
 *
 * See VESSELS in anatomy.ts for the two hilar relationships this exists to
 * draw and for every number below. Nothing here invents geometry.
 *
 * TWO GENERATORS, because they are two different kinds of structure.
 *
 * An artery is not an independent tree. It is the bronchial tree displaced by a
 * fixed small vector — that displacement IS the bronchovascular bundle, and
 * growing the arteries separately would produce a second tree that wanders off
 * its bronchi, which is the one thing a bundle never does. So the arterial
 * tree is generated by TRANSLATING the airway's own connectivity, and its
 * accuracy is inherited from the airway's rather than tuned to match it.
 *
 * A vein is an independent tree, and has to be, because it runs where the
 * bronchi are not. Its attractors are chosen for being FAR from any airway
 * node, so "veins run in the intersegmental septa" is enforced by the sampler
 * instead of asserted by a comment. Everything else is the same space
 * colonisation the airway uses, run coarser: fewer branches, longer steps.
 */

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export interface VesselSegment {
  from: Vec3;
  to: Vec3;
  /** 0 = trunk, 1 = most distal. Drives stroke weight, as generation does for the airway. */
  depth: number;
  /**
   * True for the trunk, the hilar arteries and the venous stems.
   *
   * Same reason TreeGeometry carries `central`: these run BETWEEN the lungs and
   * are legitimately outside the pleura, so the containment assertion can be
   * exact — every non-mediastinal vessel vertex must be inside a lung — rather
   * than tolerating "a few" escapees and thereby never catching a real leak.
   */
  mediastinal: boolean;
}

export interface Vessels {
  arteries: VesselSegment[];
  veins: VesselSegment[];
  /**
   * Measurements the assertion suite reads.
   *
   * Exposed rather than recomputed in the test, so the numbers asserted are the
   * ones the shipped geometry actually has — the same discipline the airway's
   * fill and containment assertions follow.
   */
  stats: {
    /** Mean distance from an arterial vertex to the nearest airway node. */
    arteryToAirway: number;
    /** The same for veins. Must exceed the arterial figure, or the septa are a fiction. */
    veinToAirway: number;
    veinNodes: number;
    /**
     * Growth nodes per vein.
     *
     * Asserted comparable across the four, because the one failure this
     * generator has actually shipped was a chest with veins down one side: the
     * right lung's deliberately denser airway starved a fixed clearance
     * threshold, and nothing in the render said so until the veins were drawn
     * on their own.
     */
    perVein: Record<keyof typeof VESSELS.ostia, number>;
  };
}

/** Catmull-Rom subdivisions per waypoint span. */
const SPLINE_STEPS = 7;

/**
 * A curve through the waypoints, not a polyline between them.
 *
 * The left pulmonary artery's whole identity is that it ARCHES. Drawn as two
 * straight runs meeting at the summit it reads as a bent wire, and the fact a
 * reader is meant to take from it — that the bronchus passes under a continuous
 * vault — is not in the picture. Catmull-Rom interpolates the waypoints exactly
 * and needs no control points invented for it, so the landmarks in anatomy.ts
 * stay the landmarks the curve passes through.
 */
function spline(points: Vec3[]): Vec3[] {
  if (points.length < 2) return [...points];
  // Duplicated ends, so the curve starts and finishes at the first and last
  // waypoints rather than one span inside them.
  const p = [points[0]!, ...points, points[points.length - 1]!];
  const out: Vec3[] = [];
  for (let i = 0; i + 3 < p.length; i++) {
    const a = p[i]!;
    const b = p[i + 1]!;
    const c = p[i + 2]!;
    const d = p[i + 3]!;
    for (let s = 0; s < SPLINE_STEPS; s++) {
      const t = s / SPLINE_STEPS;
      const t2 = t * t;
      const t3 = t2 * t;
      const at = (w: number, x: number, y: number, z: number) =>
        0.5 *
        (2 * x + (-w + y) * t + (2 * w - 5 * x + 4 * y - z) * t2 + (-w + 3 * x - 3 * y + z) * t3);
      out.push({
        x: at(a.x, b.x, c.x, d.x),
        y: at(a.y, b.y, c.y, d.y),
        z: at(a.z, b.z, c.z, d.z),
      });
    }
  }
  out.push(points[points.length - 1]!);
  return out;
}

function chain(points: Vec3[], from: number, to: number): VesselSegment[] {
  const out: VesselSegment[] = [];
  for (let i = 0; i + 1 < points.length; i++) {
    const p = points[i]!;
    const q = points[i + 1]!;
    out.push({
      from: p,
      to: q,
      depth: from + ((to - from) * i) / Math.max(1, points.length - 2),
      // Flagged for the WHOLE run, including the distal end that does enter the
      // lung. The flag exempts a class of vessel from containment, exactly as
      // TreeGeometry.central exempts a generation of airway; deriving it from
      // the containment predicate instead would make the assertion that reads
      // it vacuously true.
      mediastinal: true,
    });
  }
  return out;
}

/**
 * Distance to the nearest airway node.
 *
 * Deduplicated on the same grid the mesh uses to join the tree, so a node
 * shared by a parent and its children is counted once rather than three times —
 * which matters only for speed, but the tree has 1,597 segments and 1,189
 * distinct nodes, so it is a third of the work for free.
 *
 * Brute force after that. It is called a few thousand times at build time, and
 * a grid would buy back milliseconds at the cost of a second data structure
 * that has to stay correct.
 */
function airwayDistance(tree: TreeGeometry) {
  const seen = new Set<string>();
  const nodes: Vec3[] = [];
  const add = (x: number, y: number, z: number) => {
    const k = `${Math.round(x * 4096)},${Math.round(y * 4096)},${Math.round(z * 4096)}`;
    if (seen.has(k)) return;
    seen.add(k);
    nodes.push({ x, y, z });
  };
  for (let s = 0; s < tree.segments.length; s += 6) {
    add(tree.segments[s]!, tree.segments[s + 1]!, tree.segments[s + 2]!);
    add(tree.segments[s + 3]!, tree.segments[s + 4]!, tree.segments[s + 5]!);
  }
  return (x: number, y: number, z: number): number => {
    let best = Infinity;
    for (const p of nodes) {
      const d = Math.hypot(p.x - x, p.y - y, p.z - z);
      if (d < best) best = d;
    }
    return best;
  };
}

type VeinId = keyof typeof VESSELS.ostia;
const VEINS = Object.keys(VESSELS.ostia) as VeinId[];

export function generateVessels(tree: TreeGeometry, seed: number): Vessels {
  const rng = mulberry32(seed);
  const nearestAirway = airwayDistance(tree);

  // ── Arteries: the trunk, the two hilar vessels, then the bundle ──────────
  const arteries: VesselSegment[] = [];
  const trunk = spline([VESSELS.mpaRoot, VESSELS.mpaMid, VESSELS.mpaBifurcation]);
  const rpa = spline([VESSELS.mpaBifurcation, ...VESSELS.rpa]);
  const lpa = spline([VESSELS.mpaBifurcation, ...VESSELS.lpa]);
  const T = VESSELS.taper;
  arteries.push(...chain(trunk, 0, T.hilar));
  arteries.push(...chain(rpa, T.hilar, T.lobar));
  arteries.push(...chain(lpa, T.hilar, T.lobar));

  /**
   * The bundle: the airway's own segments, displaced.
   *
   * Side comes from the midpoint's x sign, which is safe because no
   * intrapulmonary segment crosses the midline — the mediastinum is excluded
   * from both pleural cavities, so there is a gap of 2 × LUNG.medialX that
   * nothing intrapulmonary occupies.
   */
  const offsetOf = (x: number) => (x < 0 ? VESSELS.bundleOffset.right : VESSELS.bundleOffset.left);
  const shift = (x: number, y: number, z: number, o: Vec3): Vec3 => ({
    x: x + o.x,
    y: y + o.y,
    z: z + o.z,
  });
  /** Lobar roots, so each lobe's artery can be joined to its hilar vessel. */
  const lobarRoots: Vec3[] = [];
  const maxGen = VESSELS.arteryMaxGeneration;
  for (let s = 0; s < tree.segmentGeneration.length; s++) {
    const g = tree.segmentGeneration[s]!;
    // Generations 0 and 1 are the trachea and main bronchi — mediastinal, and
    // already accompanied by the explicit trunk and hilar vessels above.
    if (g < 2 || g > maxGen) continue;
    const o = s * 6;
    const ax = tree.segments[o]!;
    const ay = tree.segments[o + 1]!;
    const az = tree.segments[o + 2]!;
    const bx = tree.segments[o + 3]!;
    const by = tree.segments[o + 4]!;
    const bz = tree.segments[o + 5]!;
    const off = offsetOf((ax + bx) / 2);
    /**
     * The offset SHRINKS rather than escaping.
     *
     * A bronchus already at the pleura has nowhere to put a vessel 0.016 units
     * outside it, and 24 segments duly ended up drawn beyond the lung — an
     * artery in the pleural space, which is a pneumothorax, not a bundle.
     * Shrinking to fit keeps the tree connected where dropping the segment
     * would leave its children floating, and it is what actually happens:
     * bronchus and artery converge as the bundle runs out of room.
     */
    const fit = (x: number, y: number, z: number): Vec3 | null => {
      for (const f of VESSELS.bundleFallbacks) {
        const c = { x: x + off.x * f, y: y + off.y * f, z: z + off.z * f };
        if (insideLung(c.x, c.y, c.z)) return c;
      }
      // Not even the bronchus itself is inside the lung. The lobar bronchi are
      // aimed rather than grown, so a few of their endpoints land marginally
      // outside — an inherited defect, and not one to compound by drawing an
      // artery in the pleural space beside it.
      return null;
    };
    const from = fit(ax, ay, az);
    const to = fit(bx, by, bz);
    if (!from || !to) continue;
    arteries.push({
      from,
      to,
      depth: T.lobar + ((1 - T.lobar) * (g - 2)) / Math.max(1, maxGen - 2),
      mediastinal: false,
    });
    if (g === 2) lobarRoots.push(from);
  }

  /**
   * Join each lobar artery to the nearest point on its hilar vessel.
   *
   * Nearest-point rather than a table of takeoffs, and it lands where anatomy
   * says it should for free: the right upper lobe's root is the most proximal
   * of the five, so it attaches to the proximal RPA — the truncus anterior —
   * while the middle and lower lobes attach distally, to the interlobar artery.
   */
  for (const root of lobarRoots) {
    const target = root.x < 0 ? rpa : lpa;
    let best = target[0]!;
    let bestD = Infinity;
    for (const p of target) {
      const d = Math.hypot(p.x - root.x, p.y - root.y, p.z - root.z);
      if (d < bestD) {
        bestD = d;
        best = p;
      }
    }
    arteries.push({ from: best, to: root, depth: T.lobar, mediastinal: true });
  }

  // ── Veins: grown where the airways are not ───────────────────────────────
  const veins: VesselSegment[] = [];
  interface Node {
    x: number;
    y: number;
    z: number;
    dx: number;
    dy: number;
    dz: number;
    vein: VeinId;
    generation: number;
  }
  const nodes: Node[] = [];
  const G = VESSELS.growth;

  for (const v of VEINS) {
    const stem = spline([VESSELS.ostia[v], ...VESSELS.stems[v]]);
    veins.push(...chain(stem, 0, T.stem));
    const tip = stem[stem.length - 1]!;
    const prev = stem[stem.length - 2] ?? VESSELS.ostia[v];
    const len = Math.hypot(tip.x - prev.x, tip.y - prev.y, tip.z - prev.z) || 1;
    nodes.push({
      x: tip.x,
      y: tip.y,
      z: tip.z,
      dx: (tip.x - prev.x) / len,
      dy: (tip.y - prev.y) / len,
      dz: (tip.z - prev.z) / len,
      vein: v,
      generation: 0,
    });
  }

  /**
   * Attractors in the septa.
   *
   * The clearance test is the mechanism, not a filter on top of one: a
   * candidate closer to a bronchus than VESSELS.septalClearance is rejected, so
   * the only places a vein can be pulled toward are places no airway reached.
   * Territory is by lobe, which is how the four veins actually divide the lung.
   */
  const attractors: { x: number; y: number; z: number; vein: VeinId; alive: boolean }[] = [];
  const C = COLONISATION;
  for (const v of VEINS) {
    const territory = VESSELS.venousTerritory[v] as readonly Lobe[];
    const pool: { x: number; y: number; z: number; d: number }[] = [];
    let guard = 0;
    while (pool.length < VESSELS.candidatesPerVein && guard++ < VESSELS.candidatesPerVein * 200) {
      const x = (rng() * 2 - 1) * C.sampleHalfX;
      const y = C.sampleMinY + rng() * C.sampleSpanY;
      const z = (rng() * 2 - 1) * C.sampleHalfZ;
      const lobe = lobeAt(x, y, z);
      if (lobe === null || !territory.includes(lobe)) continue;
      if (cardiacField(x, y, z) < 0) continue;
      pool.push({ x, y, z, d: nearestAirway(x, y, z) });
    }
    // The most septal fraction of this territory — furthest from any bronchus,
    // measured against the density this lobe actually has.
    pool.sort((a, b) => b.d - a.d);
    const keep = Math.round(pool.length * VESSELS.septalFraction);
    for (const p of pool.slice(0, keep)) {
      attractors.push({ x: p.x, y: p.y, z: p.z, vein: v, alive: true });
    }
  }

  /**
   * The hilar reach: each vein grows toward its own territory before it can
   * grow within it.
   *
   * Every hilum in this chest sits ABOVE the oblique fissure — the plane runs
   * from y = -0.17 at the front of the lung to -0.28 at the back, and the hila
   * are at -0.10 to -0.16 — so three of the four venous stems ended inside the
   * wrong lobe for their vein. With a local influence radius, none of their
   * attractors were in range and three veins grew a single segment each while
   * the fourth grew two hundred. The measurement said so plainly: rspv 1,
   * ripv 1, lspv 219, lipv 1.
   *
   * The fix is not to hand-place the stems deeper, which would be inventing
   * geometry to satisfy an algorithm. A vein really does run from the hilum
   * into its lobe before it starts collecting, and stepping toward the
   * territory's own centre of mass until the territory is in range is that
   * course, derived from the attractors rather than typed.
   */
  const REACH_STEPS = 24;
  for (const n of nodes) {
    const mine = attractors.filter((a) => a.vein === n.vein);
    if (mine.length === 0) continue;
    for (let step = 0; step < REACH_STEPS; step++) {
      // Toward the NEAREST attractor, never toward the territory's centroid.
      // A lobe is a shell around its hilum, so its centre of mass can lie in
      // the middle of the airway; stepping toward it can increase the distance
      // to every attractor at once. The nearest one is the only target whose
      // distance provably falls on each step, so the reach always terminates.
      let best = mine[0]!;
      let bestD = Infinity;
      for (const a of mine) {
        const d = Math.hypot(a.x - n.x, a.y - n.y, a.z - n.z);
        if (d < bestD) {
          bestD = d;
          best = a;
        }
      }
      if (bestD < G.influenceRadius) break;
      const dx = (best.x - n.x) / bestD;
      const dy = (best.y - n.y) / bestD;
      const dz = (best.z - n.z) / bestD;
      let to: Vec3 | null = null;
      for (const f of [1, ...C.stepFallbacks]) {
        const c = {
          x: n.x + dx * G.stepLength * f,
          y: n.y + dy * G.stepLength * f,
          z: n.z + dz * G.stepLength * f,
        };
        if (cardiacField(c.x, c.y, c.z) < 0 || !insideLung(c.x, c.y, c.z)) continue;
        to = c;
        break;
      }
      if (!to) break;
      veins.push({ from: { x: n.x, y: n.y, z: n.z }, to, depth: T.stem, mediastinal: false });
      n.x = to.x;
      n.y = to.y;
      n.z = to.z;
      n.dx = dx;
      n.dy = dy;
      n.dz = dz;
    }
  }

  for (let iter = 0; iter < G.maxIterations; iter++) {
    const pull = new Map<number, { x: number; y: number; z: number; n: number }>();
    let anyAlive = false;
    for (const a of attractors) {
      if (!a.alive) continue;
      anyAlive = true;
      let best = -1;
      let bestD: number = G.influenceRadius;
      for (let i = 0; i < nodes.length; i++) {
        const n = nodes[i]!;
        if (n.vein !== a.vein) continue;
        const d = Math.hypot(n.x - a.x, n.y - a.y, n.z - a.z);
        if (d < bestD) {
          bestD = d;
          best = i;
        }
      }
      if (best < 0) continue;
      const n = nodes[best]!;
      const len = Math.hypot(a.x - n.x, a.y - n.y, a.z - n.z) || 1;
      const acc = pull.get(best) ?? { x: 0, y: 0, z: 0, n: 0 };
      acc.x += (a.x - n.x) / len;
      acc.y += (a.y - n.y) / len;
      acc.z += (a.z - n.z) / len;
      acc.n++;
      pull.set(best, acc);
    }
    if (!anyAlive || pull.size === 0) break;

    const grown: Node[] = [];
    for (const [i, acc] of pull) {
      const n = nodes[i]!;
      /**
       * TWO HEADINGS, not one: blended with the parent, then the attractors'
       * own direction alone.
       *
       * Inertia is what makes a branch read as a continuation of its parent,
       * and it is also what can wedge a tip against a wall — a vein arriving
       * at the hilum with an anterior heading kept steering into the right
       * atrium, and the shorter fallback steps went the same way because they
       * only shorten the step, never turn it. Dropping the inertia gives the
       * tip one chance to turn away before it is declared finished, which is
       * the difference between a vein that stops at an obstacle and one that
       * runs around it.
       */
      const headings: [number, number, number][] = [];
      for (const inertia of [G.parentInertia, 0]) {
        const hx = acc.x / acc.n + n.dx * inertia;
        const hy = acc.y / acc.n + n.dy * inertia;
        const hz = acc.z / acc.n + n.dz * inertia;
        const len = Math.hypot(hx, hy, hz);
        if (len > 1e-6) headings.push([hx / len, hy / len, hz / len]);
      }
      if (headings.length === 0) continue;

      let to: Vec3 | null = null;
      let dx = 0;
      let dy = 0;
      let dz = 0;
      for (const [hx, hy, hz] of headings) {
        for (const f of [1, ...C.stepFallbacks]) {
          const c = {
            x: n.x + hx * G.stepLength * f,
            y: n.y + hy * G.stepLength * f,
            z: n.z + hz * G.stepLength * f,
          };
          if (cardiacField(c.x, c.y, c.z) < 0) continue;
          if (!insideLung(c.x, c.y, c.z)) continue;
          to = c;
          dx = hx;
          dy = hy;
          dz = hz;
          break;
        }
        if (to) break;
      }
      if (!to) continue;

      const generation = n.generation + 1;
      veins.push({
        from: { x: n.x, y: n.y, z: n.z },
        to,
        // Continues from where the stems left off, so the taper runs unbroken
        // from the atrium to the periphery rather than restarting at the hilum.
        depth: Math.min(1, T.stem + generation * T.perVenousGeneration),
        mediastinal: false,
      });
      grown.push({ ...to, dx, dy, dz, vein: n.vein, generation });
    }
    if (grown.length === 0) break;
    nodes.push(...grown);

    for (const a of attractors) {
      if (!a.alive) continue;
      for (const n of grown) {
        if (n.vein !== a.vein) continue;
        if (Math.hypot(n.x - a.x, n.y - a.y, n.z - a.z) < G.killRadius) {
          a.alive = false;
          break;
        }
      }
    }
  }

  /**
   * The separation, measured on the shipped geometry.
   *
   * Only INTRAPULMONARY vertices count on either side: the trunk, the hilar
   * arteries and the venous stems all run in the mediastinum, where there is no
   * airway to be near or far from, and including them would let a long
   * mediastinal run manufacture a separation the parenchyma does not have.
   */
  const meanDistance = (segs: VesselSegment[]) => {
    let sum = 0;
    let n = 0;
    for (const s of segs) {
      if (s.mediastinal || !insideLung(s.to.x, s.to.y, s.to.z)) continue;
      sum += nearestAirway(s.to.x, s.to.y, s.to.z);
      n++;
    }
    return n === 0 ? 0 : sum / n;
  };

  /** Venous segments per vein, so the two sides can be asserted comparable. */
  const perVein = {} as Record<VeinId, number>;
  for (const v of VEINS) perVein[v] = 0;
  for (const n of nodes) perVein[n.vein]++;

  return {
    arteries,
    veins,
    stats: {
      arteryToAirway: meanDistance(arteries),
      veinToAirway: meanDistance(veins),
      veinNodes: nodes.length,
      perVein,
    },
  };
}
